"use strict";
const $=s=>document.querySelector(s),state={mode:"agent",busy:false},form=$("#query-form"),input=$("#query-input"),messages=$("#messages"),trace=$("#trace-content"),grid=$("#song-grid"),error=$("#error-message"),send=$("#send-button");
function message(role,text){const a=document.createElement("article");a.className=`message ${role}`;if(role==="assistant"){const b=document.createElement("b");b.textContent="RockRAG";a.append(b)}const p=document.createElement("p");p.textContent=text;a.append(p);messages.append(a);messages.scrollTop=messages.scrollHeight}
function busy(value){state.busy=value;send.disabled=value;input.disabled=value;$("#send-label").textContent=value?"Working…":"Send"}
function findSongs(value,out=[]){if(Array.isArray(value))value.forEach(x=>findSongs(x,out));else if(value&&typeof value==="object"){if(typeof value.song_id==="string"&&typeof value.title==="string"&&typeof value.artist==="string")out.push(value);Object.values(value).forEach(x=>findSongs(x,out))}return out}
function renderSongs(raw){const map=new Map;findSongs(raw).forEach(s=>map.set(s.song_id,s));const songs=[...map.values()];grid.replaceChildren();$("#result-count").textContent=songs.length?`${songs.length} catalog tracks`:"No results";if(!songs.length){const p=document.createElement("p");p.className="no-results";p.textContent="No structured song results were returned.";grid.append(p);return}songs.forEach((s,i)=>{const card=document.createElement("article");card.className="song-card";card.style.setProperty("--card-accent",`hsl(${(i*47+s.artist.length*11)%360} 72% 62%)`);const initial=document.createElement("div");initial.className="initial";initial.textContent=s.artist[0].toUpperCase();const title=document.createElement("h3");title.textContent=s.title;const artist=document.createElement("p");artist.className="artist";artist.textContent=s.artist;const meta=document.createElement("p");meta.className="meta";meta.textContent=[s.release_year,...(s.genres||[])].filter(Boolean).join(" · ");const tags=document.createElement("div");tags.className="tags";(s.tags||[]).slice(0,5).forEach(t=>{const x=document.createElement("span");x.textContent=t;tags.append(x)});card.append(initial,title,artist,meta,tags);if(Number.isFinite(s.reranker_score)){const score=document.createElement("p");score.className="score";score.textContent=`Reranker score: ${s.reranker_score.toFixed(4)}`;card.append(score)}grid.append(card)})}
function renderTrace(calls,results){trace.replaceChildren();trace.className=calls.length?"trace-list":"empty";$("#trace-count").textContent=`${calls.length} ${calls.length===1?"call":"calls"}`;if(!calls.length){const p=document.createElement("p");p.textContent="No catalog tool call in this response.";trace.append(p);return}calls.forEach((call,i)=>{const result=results[i],card=document.createElement("article");card.className="trace-step";const h=document.createElement("header"),step=document.createElement("span"),tool=document.createElement("strong");step.textContent=`Step ${call.step}`;tool.textContent=call.tool;h.append(step,tool);const args=document.createElement("pre");args.textContent=JSON.stringify(call.arguments,null,2);const d=document.createElement("details"),summary=document.createElement("summary"),raw=document.createElement("pre"),n=result?findSongs(result.result).length:0;summary.textContent=n?`Returned ${n} song${n===1?"":"s"} · View JSON`:"View tool result";raw.textContent=JSON.stringify(result?.result??null,null,2);d.append(summary,raw);card.append(h,args,d);trace.append(card)})}
async function json(url,options={}){const response=await fetch(url,options),data=await response.json().catch(()=>({detail:"Server returned non-JSON data."}));if(!response.ok)throw new Error(data.detail||data.error||`HTTP ${response.status}`);return data}
async function submit(query){busy(true);error.textContent="";message("user",query);try{if(state.mode==="agent"){const d=await json("/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:query})});message("assistant",d.answer);renderTrace(d.tool_calls,d.tool_results);renderSongs(d.tool_results)}else{const d=await json("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,top_k:10})});message("assistant",`Found ${d.results.length} reranked catalog tracks in ${d.latency_seconds.toFixed(3)} seconds.`);renderTrace([],[]);renderSongs(d.results)}}catch(e){error.textContent=e.message;message("assistant",`Request unavailable: ${e.message}`)}finally{busy(false);input.focus()}}
form.addEventListener("submit",e=>{e.preventDefault();const q=input.value.trim();if(!q||state.busy)return;input.value="";submit(q)});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});document.querySelectorAll(".chips button").forEach(b=>b.addEventListener("click",()=>{input.value=b.textContent;input.focus()}));document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>{state.mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>{const active=x===b;x.classList.toggle("active",active);x.setAttribute("aria-selected",String(active))});$("#mode-title").textContent=state.mode==="agent"?"Agent":"Search"}));
(async()=>{const dot=$("#status-dot");try{const h=await json("/health");$("#catalog-size").textContent=`${h.catalog_size} songs`;$("#model-name").textContent=h.llm_model;$("#ollama-status").textContent=h.ollama_reachable?"Ollama online":"Ollama offline";dot.className=h.ollama_reachable?"online":"offline"}catch{$("#ollama-status").textContent="API unavailable";dot.className="offline"}})();
